name: compass-circular-slider

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use your desired Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Bump version based on commit message
      - name: Bump version
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[major]"* ]]; then
            npm version major
          elif [[ "${{ github.event.head_commit.message }}" == *"[minor]"* ]]; then
            npm version minor
          else
            npm version patch
          fi

      # Build the package
      - name: Build the package
        run: npm run build

      # Publish to npm
      - name: Publish to npm
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
